[Version]
Class=IEXPRESS
SEDVersion=3
[Options]
PackagePurpose=CreatePackage
ShowInstallProgramWindow=0
HideExtractAnimation=1
UseLongFileName=1
InsideCompressed=0
CAB_FixedSize=0
CAB_ResvCodeSigning=0
RebootMode=N
InstallPrompt=
DisplayLicense=
FinishMessage=
TargetName=C:\Users\admin\Doubao\chats\2026-09-16\new-chat-2\NetDiag.exe
FriendlyName=NetDiag
AppLaunched=net_diag.bat
PostInstallCmd=<None>
AdminQuietInstCmd=
UserQuietInstCmd=
SourceFiles=SourceFiles
[Strings]
SourceFiles0=C:\Users\admin\Doubao\chats\2026-09-16\new-chat-2\pack\
[SourceFiles0]
%FILE0%=net_diag.bat
